// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2992.StarLord2019;



/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class Constants {
    public static final int driveEncDist = 4096;

    public static final double normalLiftUpSpeed = 0.8;//.9
    public static final double normalLiftDownSpeed = 0.4;
    
    //Cargo lift heights
    public static final double topRocketCargoHeight = 65;//66 
    public static final double middleRocketCargoHeight = 37;//38
    public static final double bottomRocketCargoHeight = 9;//10
    public static final double cargoLoadHeight = 26.5;//27.5
    public static final double cargoGroundHeight = 0;

    //Hatch lift heights
    public static final double topRocketHatchHeight = 55;//56
    public static final double middleRocketHatchHeight = 27;//28
    public static final double bottomRocketHatchHeight = 0;

    public static final double hatchLoadingGrabTimeout = 0.3;
    public static final double liftTimeout = 0.5;

    //VP Constants
    public static final double camHt = 0;
    public static final double tarHt = 0;
    public static final double camAngle = 0;

    //Climb speeds
    public static double upClimbSpeed = .75;//1
    public static double downClimbSpeed = -.75;//-.3
    public static double rollCorrection = -3;

}

